[package]
name = "gui-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.14.2"
raw-window-handle = "0.5.0"
bytemuck = { version = "1.12.3", features = [ "derive" ]}